### ISSUE TITLE
support ArchGDAL v0.7.0

### ISSUE THREAD

**Issue by kongdd** [evetion/GeoDataFrames.jl#18]
https://github.com/yeesian/ArchGDAL.jl

**Comment by visr** [comment]
This package does not yet support ArchGDAL 0.7, so unless you are explicitly using ArchGDAL master or dev'ed the package, there shouldn't be any problems, right?
https://github.com/evetion/GeoDataFrames.jl/blob/a6ec96bb0a2f4dc0f86304e1b67582525e7ac48b/Project.toml#L14

But from https://github.com/yeesian/ArchGDAL.jl/pull/179, this should be the fix:

`_FIELDTYPE[fieldtype] -> convert(DataType, fieldtype)`

And this:
https://github.com/evetion/GeoDataFrames.jl/blob/a6ec96bb0a2f4dc0f86304e1b67582525e7ac48b/src/io.jl#L14-L15
can become

`table = AG.getlayer(ds, layer)`

**Comment by evetion** [comment]
Fixed by #21
