### ISSUE TITLE
isempty export

### ISSUE THREAD

**Issue by visr** [evetion/GeoDataFrames.jl#27]
I noticed that this package re-exports `isempty` from ArchGDAL. In ArchGDAL it is not exported.

It is unfortunate however to export something that is also exported from Base, leading to

```
WARNING: both GeoDataFrames and Base export "isempty"; uses of it in module Main must be qualified
ERROR: UndefVarError: isempty not defined
```

**Comment by evetion** [comment]
Fixed in https://github.com/evetion/GeoDataFrames.jl/commit/e1a55d463420e1444eb7c5208acf7526233622d8 and released in [v0.2.0](https://github.com/evetion/GeoDataFrames.jl/releases/tag/v0.2.0).
