### ISSUE TITLE
Pointer 'hDefn' is NULL in 'OGR_F_Create'

### ISSUE THREAD

**Issue by crabbixOCE** [evetion/GeoDataFrames.jl#56]
This error gets thrown when I try to use GeoDataFrames.write() with the .gpkg or .shp file formats. I am certain that it is not a problem with the data, as this error occurs even when trying to write a dataframe that has just been read unmodified from a working .gpkg file. Function was previously working, but has broken after I tried to install the Turf.jl package

**Comment by evetion** [comment]
Thanks for reporting! Maybe something changed in your environment? Can you check you have the latest version with posting the output of Pkg.status() (or ]st) here?

Otherwise, it's probably something special with your data, and posting a file, or describing the schema would help.

**Comment by visr** [comment]
Probably the reason is that Turf.jl is not compatible with GeoInterface v1, and therefore downgrading GDAL related packages to a really old version.

I assume there isn't really much we can do besides updating Turf.jl.

https://github.com/philoez98/Turf.jl/blob/v0.2.1/Project.toml

**Comment by crabbixOCE** [comment]
Yeah, looks like installing Turf.jl downgraded me to GeoDataFrames 0.2.4 and ArchGDAL 0.8.6. Updating both packages to their latest versions fixed the issue - although when I tried to do this with `]up GeoDataFrames` it didn't work, I had to specify the version with `]add GeoDataFrames@0.3.6`
