### ISSUE TITLE
`isgeometry` check accidentally gets columns with vector values

### ISSUE THREAD

**Issue by asinghvi17** [evetion/GeoDataFrames.jl#77]
MWE:
```julia
using GeometryBasics, GeoDataFrames
df = DataFrame(geometry = rand(Point2f, 100))
df.area_km2 = [rand(10) for i in 1:100]

GeoDataFrames.write("test.gpkg", df)
```

https://github.com/evetion/GeoDataFrames.jl/blob/9512d12a3b13aecafafb84984de750f54d601e4c/src/io.jl#L163-L165

**Comment by asinghvi17** [comment]
cc @alex-s-gardner

**Comment by evetion** [comment]
I presume this errors, no? We can't change isgeometry, but we can be more lenient in the check and just try to write.
