### ISSUE TITLE
Confusing read() error for absolute Windows path arg

### ISSUE THREAD

**Issue by arlowhite** [evetion/GeoDataFrames.jl#78]
GeoDataFrames version 0.3.10

In Windows, if you call `read` with an absolute path where file does not exist, you get a confusing error. This could confuse and frustrate Windows users.

`GeoDataFrames.read("C:\\foo")`
> ERROR: GDALError (CE_Failure, code 10):
        Pointer 'hDS' is NULL in 'GDALDatasetH'.

This is due to the colon in the file path.

https://github.com/evetion/GeoDataFrames.jl/blob/master/src/io.jl#L52

```julia
function read(fn::AbstractString; kwargs...)
    startswith(fn, "/vsi") ||
        occursin(":", fn) ||
        isfile(fn) ||
        isdir(fn) ||
        error("File not found.")
    t = AG.read(fn; kwargs...) do ds
        if AG.nlayer(ds) > 1
            @warn "This file has multiple layers, you only get the first layer by default now."
        end
        return read(ds, 0)
    end
    return t
end
```

----
`:` in `fn` causes error to be skipped at ` occursin(":", fn)` . Then `AG.nlayer(ds)` results in this confusing error.
`ds`
> NULL Dataset

`typeof(ds)`
> ArchGDAL.Dataset

Note: you could check for NULL Dataset with `ds.ptr == C_NULL`

**Comment by evetion** [comment]
Thanks for reporting! With adding : I overlooked Windows paths it seems. Would you like to make a PR?
