### ISSUE TITLE
Change some args in `write` to be keyword?

### ISSUE THREAD

**Issue by vlandau** [evetion/GeoDataFrames.jl#8]
Wondering if it might make it easier on the user to have some of the arguments to [`write`](https://github.com/evetion/GeoDataFrames.jl/blob/4f1d2b59191d569f6e0999705f6fb7b73cb74776/src/io.jl#L21) be keywords? 

Then the user wouldn't have to specify every argument if they only want to change, e.g., crs or driver.

**Comment by evetion** [comment]
Sure, do you propose to make all parameters except the first two keyword arguments?

**Comment by visr** [comment]
Clicking that link I'm mainly surprised by this default: `crs::GFT.GeoFormat=GFT.EPSG(4326)`. Isn't no CRS better than wrong CRS?

**Comment by vlandau** [comment]
> Sure, do you propose to make all parameters except the first two keyword arguments?

Yep :point_up:  that's exactly what I was thinking.

@visr I would agree that no CRS would be better, and hopefully this will become even less of an issue once projection info is stored inside the GeoDataFrame itself, which I believe is the plan.

**Comment by evetion** [comment]
The keywords are fixed in the latest release. The default projection isn't yet fixed, but is now an issue: #9.
